FROM mysql:5.7
ADD ./my.cnf /etc/mysql/conf.d/my.cnf

ENV LC_ALL=C.UTF-8
ENV character-set-server utf8
ENV collation-server utf8_general_ci
ENV default-character-set utf8
ENV default-collation utf8_general_ci
